### ISSUE TITLE
TypeScript projects don't compile with version 2.1.3

### ISSUE THREAD

**Issue by yotamshapira** [humanwhocodes/env#16]
When building a TypeScript project using version 2.1.3 (doesn't reproduce with 2.1.2), I get the following compilation errors:
```
Error: node_modules/@humanwhocodes/env/dist/env.d.ts(2,12): error TS2395: Individual declarations in merged declaration 'Env' must be all exported or all local.
Error: node_modules/@humanwhocodes/env/dist/env.d.ts(2,12): error TS2502: 'Env' is referenced directly or indirectly in its own type annotation.
Error: node_modules/@humanwhocodes/env/dist/env.d.ts(6,15): error TS2395: Individual declarations in merged declaration 'Env' must be all exported or all local.
```

I created a repo reproducing this: https://github.com/yotamshapira/env-2-1-3-build-demo
You can see the build error here: https://github.com/yotamshapira/env-2-1-3-build-demo/pull/2/checks?check_run_id=2019693840

**Comment by robcresswell** [comment]
Just wanted to confirm this. The types that are part of the built package seem to be invalid

**Comment by nzakas** [comment]
Hmm that is strange. Thanks for the heads up, I’ll take a look.

**Comment by nzakas** [comment]
This should be fixed in v2.1.4, but let me know if you are still having any problems.
